In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
sales_df = pd.read_csv("H:\Barbosa\Downloads\SalesData.csv")
sales_df.reset_index(drop = True, inplace = True)

In [3]:
print(sales_df)

     Temperature     Revenue
0      24.566884  534.799028
1      26.005191  625.190122
2      27.790554  660.632289
3      20.595335  487.706960
4      11.503498  316.240194
..           ...         ...
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

[500 rows x 2 columns]


In [4]:
X_train = sales_df['Temperature']
Y_train = sales_df['Revenue']

In [10]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units = 10, input_shape = [1]))
model.add(tf.keras.layers.Dense(units = 1))

In [11]:
model.compile(optimizer = tf.keras.optimizers.Adam(0.1), loss='mean_squared_error')

In [12]:
epoch_hist = model.fit(x = X_train, y = Y_train, epochs = 1000)

Epoch 1/1000
16/16 [==============================] - 1s 2ms/step - loss: 187534.1406
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 17621.3691
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 6459.6069
Epoch 4/1000
16/16 [==============================] - 0s 2ms/step - loss: 3615.0967
Epoch 5/1000
16/16 [==============================] - 0s 2ms/step - loss: 3157.1628
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 2835.1453
Epoch 7/1000
16/16 [==============================] - 0s 2ms/step - loss: 2779.5342
Epoch 8/1000
16/16 [==============================] - 0s 2ms/step - loss: 2767.5813
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 2848.8972
Epoch 10/1000
16/16 [==============================] - 0s 2ms/step - loss: 2765.4055
Epoch 11/1000
16/16 [==============================] - 0s 2ms/step - loss: 2829.6436
Epoch 12/1000
16/16 [==============================] - 0s 1ms/step - lo

16/16 [==============================] - 0s 2ms/step - loss: 2816.8313
Epoch 98/1000
16/16 [==============================] - 0s 2ms/step - loss: 2799.4019
Epoch 99/1000
16/16 [==============================] - 0s 2ms/step - loss: 2981.0737
Epoch 100/1000
16/16 [==============================] - 0s 2ms/step - loss: 3143.4504
Epoch 101/1000
16/16 [==============================] - 0s 3ms/step - loss: 2939.0234
Epoch 102/1000
16/16 [==============================] - 0s 3ms/step - loss: 3124.2705
Epoch 103/1000
16/16 [==============================] - 0s 2ms/step - loss: 2782.1113
Epoch 104/1000
16/16 [==============================] - 0s 1ms/step - loss: 2852.8645
Epoch 105/1000
16/16 [==============================] - 0s 1ms/step - loss: 3176.0959
Epoch 106/1000
16/16 [==============================] - 0s 3ms/step - loss: 2826.2446
Epoch 107/1000
16/16 [==============================] - 0s 1ms/step - loss: 2844.9041
Epoch 108/1000
16/16 [==============================] - 0s 2ms/step - l

16/16 [==============================] - 0s 2ms/step - loss: 2701.4873
Epoch 193/1000
16/16 [==============================] - 0s 1ms/step - loss: 2828.7119
Epoch 194/1000
16/16 [==============================] - 0s 2ms/step - loss: 2900.4482
Epoch 195/1000
16/16 [==============================] - 0s 2ms/step - loss: 2756.3713
Epoch 196/1000
16/16 [==============================] - 0s 2ms/step - loss: 2917.0337
Epoch 197/1000
16/16 [==============================] - 0s 2ms/step - loss: 2906.6802
Epoch 198/1000
16/16 [==============================] - 0s 2ms/step - loss: 3250.6587
Epoch 199/1000
16/16 [==============================] - 0s 2ms/step - loss: 3034.0667
Epoch 200/1000
16/16 [==============================] - 0s 1ms/step - loss: 2783.3555
Epoch 201/1000
16/16 [==============================] - 0s 1ms/step - loss: 2821.0701
Epoch 202/1000
16/16 [==============================] - 0s 2ms/step - loss: 2856.7776
Epoch 203/1000
16/16 [==============================] - 0s 2ms/step -

16/16 [==============================] - 0s 2ms/step - loss: 2731.5920
Epoch 288/1000
16/16 [==============================] - 0s 2ms/step - loss: 2879.1604
Epoch 289/1000
16/16 [==============================] - 0s 1ms/step - loss: 2885.3979
Epoch 290/1000
16/16 [==============================] - 0s 2ms/step - loss: 3227.0205
Epoch 291/1000
16/16 [==============================] - 0s 2ms/step - loss: 2785.0378
Epoch 292/1000
16/16 [==============================] - 0s 2ms/step - loss: 2951.0635
Epoch 293/1000
16/16 [==============================] - 0s 2ms/step - loss: 3299.2581
Epoch 294/1000
16/16 [==============================] - 0s 2ms/step - loss: 2837.6089
Epoch 295/1000
16/16 [==============================] - 0s 2ms/step - loss: 3296.3899
Epoch 296/1000
16/16 [==============================] - 0s 2ms/step - loss: 3395.6772
Epoch 297/1000
16/16 [==============================] - 0s 2ms/step - loss: 3301.0845
Epoch 298/1000
16/16 [==============================] - 0s 2ms/step -

16/16 [==============================] - 0s 1ms/step - loss: 2863.2207
Epoch 383/1000
16/16 [==============================] - 0s 1ms/step - loss: 2781.2117
Epoch 384/1000
16/16 [==============================] - 0s 1ms/step - loss: 2903.9209
Epoch 385/1000
16/16 [==============================] - 0s 1ms/step - loss: 2904.6387
Epoch 386/1000
16/16 [==============================] - 0s 1ms/step - loss: 2766.6953
Epoch 387/1000
16/16 [==============================] - 0s 1ms/step - loss: 2822.2852
Epoch 388/1000
16/16 [==============================] - 0s 2ms/step - loss: 2965.1333
Epoch 389/1000
16/16 [==============================] - 0s 1ms/step - loss: 3106.6687
Epoch 390/1000
16/16 [==============================] - 0s 1ms/step - loss: 2898.1909
Epoch 391/1000
16/16 [==============================] - 0s 2ms/step - loss: 2900.1243
Epoch 392/1000
16/16 [==============================] - 0s 2ms/step - loss: 2920.6716
Epoch 393/1000
16/16 [==============================] - 0s 2ms/step -

16/16 [==============================] - 0s 2ms/step - loss: 3002.7065
Epoch 478/1000
16/16 [==============================] - 0s 2ms/step - loss: 2700.7664
Epoch 479/1000
16/16 [==============================] - 0s 2ms/step - loss: 2949.0449
Epoch 480/1000
16/16 [==============================] - 0s 2ms/step - loss: 2827.1401
Epoch 481/1000
16/16 [==============================] - 0s 2ms/step - loss: 2750.9795
Epoch 482/1000
16/16 [==============================] - 0s 2ms/step - loss: 2766.2046
Epoch 483/1000
16/16 [==============================] - 0s 2ms/step - loss: 2853.8816
Epoch 484/1000
16/16 [==============================] - 0s 1ms/step - loss: 2965.2241
Epoch 485/1000
16/16 [==============================] - 0s 1ms/step - loss: 2768.0439
Epoch 486/1000
16/16 [==============================] - 0s 3ms/step - loss: 2685.4929
Epoch 487/1000
16/16 [==============================] - 0s 2ms/step - loss: 2672.0789
Epoch 488/1000
16/16 [==============================] - 0s 2ms/step -

16/16 [==============================] - 0s 1ms/step - loss: 2718.7446
Epoch 573/1000
16/16 [==============================] - 0s 1ms/step - loss: 2849.4561
Epoch 574/1000
16/16 [==============================] - 0s 1ms/step - loss: 2825.8044
Epoch 575/1000
16/16 [==============================] - 0s 1ms/step - loss: 2745.9087
Epoch 576/1000
16/16 [==============================] - 0s 2ms/step - loss: 2768.0374
Epoch 577/1000
16/16 [==============================] - 0s 1ms/step - loss: 2718.4272
Epoch 578/1000
16/16 [==============================] - 0s 1ms/step - loss: 2920.2512
Epoch 579/1000
16/16 [==============================] - 0s 2ms/step - loss: 2769.2263
Epoch 580/1000
16/16 [==============================] - 0s 2ms/step - loss: 2821.2427
Epoch 581/1000
16/16 [==============================] - 0s 1ms/step - loss: 2760.8093
Epoch 582/1000
16/16 [==============================] - 0s 2ms/step - loss: 3086.9429
Epoch 583/1000
16/16 [==============================] - 0s 1ms/step -

16/16 [==============================] - 0s 2ms/step - loss: 2808.3076
Epoch 668/1000
16/16 [==============================] - 0s 1ms/step - loss: 2838.8838
Epoch 669/1000
16/16 [==============================] - 0s 1ms/step - loss: 2881.8894
Epoch 670/1000
16/16 [==============================] - 0s 2ms/step - loss: 3151.4595
Epoch 671/1000
16/16 [==============================] - 0s 1ms/step - loss: 2870.5337
Epoch 672/1000
16/16 [==============================] - 0s 1ms/step - loss: 2592.2275
Epoch 673/1000
16/16 [==============================] - 0s 2ms/step - loss: 2789.1150
Epoch 674/1000
16/16 [==============================] - 0s 2ms/step - loss: 2697.6055
Epoch 675/1000
16/16 [==============================] - 0s 1ms/step - loss: 2803.7266
Epoch 676/1000
16/16 [==============================] - 0s 1ms/step - loss: 2804.4060
Epoch 677/1000
16/16 [==============================] - 0s 1ms/step - loss: 2680.3279
Epoch 678/1000
16/16 [==============================] - 0s 1ms/step -

16/16 [==============================] - 0s 1ms/step - loss: 2724.8472
Epoch 763/1000
16/16 [==============================] - 0s 1ms/step - loss: 2705.1973
Epoch 764/1000
16/16 [==============================] - 0s 1ms/step - loss: 2784.9668
Epoch 765/1000
16/16 [==============================] - 0s 1ms/step - loss: 2818.3623
Epoch 766/1000
16/16 [==============================] - 0s 1ms/step - loss: 2704.2437
Epoch 767/1000
16/16 [==============================] - 0s 1ms/step - loss: 2691.5337
Epoch 768/1000
16/16 [==============================] - 0s 1ms/step - loss: 2900.7871
Epoch 769/1000
16/16 [==============================] - 0s 2ms/step - loss: 2771.4797
Epoch 770/1000
16/16 [==============================] - 0s 1ms/step - loss: 2837.8772
Epoch 771/1000
16/16 [==============================] - 0s 1ms/step - loss: 2940.3406
Epoch 772/1000
16/16 [==============================] - 0s 1ms/step - loss: 3105.6172
Epoch 773/1000
16/16 [==============================] - 0s 1ms/step -

16/16 [==============================] - 0s 1ms/step - loss: 2702.6963
Epoch 858/1000
16/16 [==============================] - 0s 1ms/step - loss: 2852.4248
Epoch 859/1000
16/16 [==============================] - 0s 1ms/step - loss: 2818.2224
Epoch 860/1000
16/16 [==============================] - 0s 1ms/step - loss: 2905.5100
Epoch 861/1000
16/16 [==============================] - 0s 1ms/step - loss: 2672.9119
Epoch 862/1000
16/16 [==============================] - 0s 1ms/step - loss: 2724.5435
Epoch 863/1000
16/16 [==============================] - 0s 1ms/step - loss: 2845.3899
Epoch 864/1000
16/16 [==============================] - 0s 1ms/step - loss: 2950.9475
Epoch 865/1000
16/16 [==============================] - 0s 2ms/step - loss: 2899.8423
Epoch 866/1000
16/16 [==============================] - 0s 1ms/step - loss: 2775.8506
Epoch 867/1000
16/16 [==============================] - 0s 1ms/step - loss: 2888.1355
Epoch 868/1000
16/16 [==============================] - 0s 1ms/step -

16/16 [==============================] - 0s 1ms/step - loss: 2816.0093
Epoch 953/1000
16/16 [==============================] - 0s 1ms/step - loss: 2820.3057
Epoch 954/1000
16/16 [==============================] - 0s 1ms/step - loss: 2664.0815
Epoch 955/1000
16/16 [==============================] - 0s 1ms/step - loss: 2680.9048
Epoch 956/1000
16/16 [==============================] - 0s 2ms/step - loss: 2774.5710
Epoch 957/1000
16/16 [==============================] - 0s 1ms/step - loss: 2705.7715
Epoch 958/1000
16/16 [==============================] - 0s 1ms/step - loss: 2708.4675
Epoch 959/1000
16/16 [==============================] - 0s 2ms/step - loss: 2718.4521
Epoch 960/1000
16/16 [==============================] - 0s 2ms/step - loss: 2731.6606
Epoch 961/1000
16/16 [==============================] - 0s 1ms/step - loss: 2736.9668
Epoch 962/1000
16/16 [==============================] - 0s 1ms/step - loss: 2711.4707
Epoch 963/1000
16/16 [==============================] - 0s 1ms/step -

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                20        
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.get_weights()


[array([[ 1.02999695e-01, -1.72019638e-02,  4.52698946e+00,
          3.87360621e-03, -1.91301908e-02, -2.61026085e-03,
          2.47185235e-03, -1.07657891e-02,  1.16826938e-02,
         -2.04545464e-02]], dtype=float32),
 array([-2.996475  ,  0.70189804,  8.584746  , -0.14251743,  0.78981614,
         0.1261416 ,  0.18900028,  0.75122464, -0.675193  ,  0.6465132 ],
       dtype=float32),
 array([[-7.5400933e-03],
        [ 1.1713463e-02],
        [ 4.6417494e+00],
        [-3.0582247e-03],
        [ 9.7441943e-03],
        [ 2.1451188e-03],
        [ 8.5624855e-04],
        [ 2.1271715e-02],
        [-1.5823383e-02],
        [ 5.4918965e-03]], dtype=float32),
 array([19.10292], dtype=float32)]

In [15]:
model.get_weights()

[array([[ 1.02999695e-01, -1.72019638e-02,  4.52698946e+00,
          3.87360621e-03, -1.91301908e-02, -2.61026085e-03,
          2.47185235e-03, -1.07657891e-02,  1.16826938e-02,
         -2.04545464e-02]], dtype=float32),
 array([-2.996475  ,  0.70189804,  8.584746  , -0.14251743,  0.78981614,
         0.1261416 ,  0.18900028,  0.75122464, -0.675193  ,  0.6465132 ],
       dtype=float32),
 array([[-7.5400933e-03],
        [ 1.1713463e-02],
        [ 4.6417494e+00],
        [-3.0582247e-03],
        [ 9.7441943e-03],
        [ 2.1451188e-03],
        [ 8.5624855e-04],
        [ 2.1271715e-02],
        [-1.5823383e-02],
        [ 5.4918965e-03]], dtype=float32),
 array([19.10292], dtype=float32)]